name: wheatwise
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bcrypt: ^1.1.3
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  connectivity_plus: ^6.0.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.1

  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  flutter_image_compress: ^2.2.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  iconsax: ^0.0.8
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  jumping_dot: ^0.0.6
  page_view_indicators: ^2.0.0
  path: ^1.9.0
  path_provider: ^2.1.2
  photo_view: ^0.14.0
  readmore: ^3.0.0
  share_plus: ^8.0.2
  shared_preferences: ^2.2.2
  syncfusion_flutter_charts: ^25.1.39+1
  tflite_v2: ^1.0.0
  uuid: ^4.3.3

dev_dependencies:
  build_runner: null
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

  hive_generator: null

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - assets/icons/
    - assets/model/
    - .env

  fonts:
    - family: Clash Display
      fonts:
        - asset: assets/fonts/ClashDisplay/ClashDisplayBold.otf
        - asset: assets/fonts/ClashDisplay/ClashDisplayExtralight.otf
        - asset: assets/fonts/ClashDisplay/ClashDisplayLight.otf
        - asset: assets/fonts/ClashDisplay/ClashDisplayMedium.otf
        - asset: assets/fonts/ClashDisplay/ClashDisplayRegular.otf
        - asset: assets/fonts/ClashDisplay/ClashDisplaySemibold.otf

    - family: SF-Pro-Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text/SF-Pro-Text-Bold.otf
        - asset: assets/fonts/SF-Pro-Text/SF-Pro-Text-Heavy.otf
        - asset: assets/fonts/SF-Pro-Text/SF-Pro-Text-Light.otf
        - asset: assets/fonts/SF-Pro-Text/SF-Pro-Text-Medium.otf
        - asset: assets/fonts/SF-Pro-Text/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text/SF-Pro-Text-Semibold.otf
